server:
  port: 8081
spring:
  thymeleaf:
    cache: false
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true # we use gulp + BrowserSync for livereload

  datasource:
          type: com.zaxxer.hikari.HikariDataSource
          url: jdbc:mysql://localhost:3306/catalogservice?useUnicode=true&characterEncoding=utf8&useSSL=false
          username: root
          password: admin
          hikari:
              data-source-properties:
                  cachePrepStmts: true
                  prepStmtCacheSize: 250
                  prepStmtCacheSqlLimit: 2048
                  useServerPrepStmts: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: MYSQL
    show-sql: true
    properties:
      hibernate.id.new_generator_mappings: true